name: macos-15-intel

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: macos-15-intel-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      os: macos-15-intel
      compilers: '["clang++"]'
